language: node_js
node_js:
  - "0.10"
env:
  global:
    - GHPAGES=".gh-pages"
    - secure: "ZguNnybtl6L0Ww7IO8+wol2r/OZcr39ADAm+sT3hYDHbMV7z5SMP2oJLT4jyeudPMhpdyrkGUygjMY6ofAj6QjFEjhWXIJNnRR5eh0sMDBD3+aa/UnDq0zymMt/VCeg0JPN+RpizwLnEv+i/QfoWmAsZwpLheKGUW+//GP8CsYk="
    - SAUCE_USERNAME="webpro"
    - secure: "JFR5yb2JmkzHPQY0KigOXX92B4CRbKI61Dq84+Rs+f69ekpfy1CRLcUfBuT1TzkcrkSnMj/CQjILK9ll6EZMmodxvzDpSw6sgiqwF2/XAaEchxpcFXdjA0Fvyo5h2ZwLWaOYWjDCKczAYLkT5Mj/oRd2orYbTqj+9PTo3W1Cv+E="
    - COVERALLS_SERVICE_NAME=travis-ci
    - secure: "NGCnYXwPfpdiu7ssBpjnhtB8Wvwlsnue2b/qdCsMZ6z8KDehvGUYCWAXrJPrWFbIKm05ksweju9tXLWA0xYwrG+bJFhwJoABNsImXtrZepwMiZAElXzMc8TZdH2MPmIa5BVgEyil4Ju94eUrRL/yXq7Qpw484OIdXIRnjELDgHM="
branches:
  except:
    - dev
before_install:
  - "npm i coveralls@2.11.2 ecstatic@0.5.8 request@2.51.0 sauce-tunnel@2.1.1"
script:
  - "npm test"
after_success:
  - "npm run coverage"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "git config --global user.email \"travis@travis-ci.org\" && git config --global user.name \"travis-ci\""
  - "git clone --branch=gh-pages https://${GH_TOKEN}@github.com/webpro/DOMtastic.git $GHPAGES"
  - "cat $GHPAGES/index.yml README.md > $GHPAGES/index.md"
  - "rsync --recursive --delete dist/ $GHPAGES/dist/"
  - "rsync --recursive --delete test/ $GHPAGES/test/"
  - "rsync --recursive --delete benchmark/ $GHPAGES/benchmark/"
  - "rsync --recursive --delete vendor/ $GHPAGES/vendor/"
  - "rsync --recursive --delete coverage/lcov-report/ $GHPAGES/coverage/"
  - "cp coverage/coverage.json coverage/lcov.info $GHPAGES/coverage/"
  - "rm -rf $GHPAGES/doc && ./node_modules/doxstrap/bin/doxstrap.js --title DOMtastic --output $GHPAGES/doc"
  - "npm run transpile"
  - "cd dist/commonjs && ../../node_modules/plato/bin/plato -r -d ../../$GHPAGES/complexity --jshint ../../.jshintrc ."
  - "cd $TRAVIS_BUILD_DIR"
  - "node test/lib/sauce.js"
  - "cd $GHPAGES && git add --all && git commit -m \"Update all the things\" && git push -fq origin gh-pages > /dev/null"
  - "cd $TRAVIS_BUILD_DIR"
